name: social-media
services:
    server:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=!SocialMedia1
            - MSSQL_PID=Evaluation
        ports:
            - 1433:1433
        container_name: socialmedia
        hostname: socialmedia
        image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04